### ISSUE TITLE
搞个订阅

### ISSUE THREAD

**Issue by FLHonker** [umelabs/node.umelabs.dev#1]
用base64编码搞个订阅链接啊老哥！

**Comment by umelabs** [comment]
你是说这个项目地址的订阅链接？

**Comment by FLHonker** [comment]
> 你是说这个项目地址的订阅链接？
不是撒，是每组节点链接搞成订阅地址形式，方便用户自动更新节点，不用每次都导入了。

**Comment by FLHonker** [comment]
看这个教程吧：<https://www.ofofree.com/vpsfree/02/26/%e5%88%b6%e4%bd%9cssr%e5%92%8cv2ray%e8%ae%a2%e9%98%85%e9%93%be%e6%8e%a5%e8%b6%85%e7%ae%80%e5%8d%95%e8%af%a6%e7%bb%86%e6%95%99%e7%a8%8b/>

**Comment by umelabs** [comment]
[https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/v2ray.md](url)
你看看可不可以用 @FLHonker

**Comment by FLHonker** [comment]
> [https://raw.githubusercontent.com/umelabs/node.umelabs.dev/master/Subscribe/v2ray.md](url)
> 你看看可不可以用 @FLHonker

很可以，稳得一批。每天更新链接文件就可以很方便了。

**Comment by FLHonker** [comment]
不过这服务器节点被封了呀，不能用了。

**Comment by umelabs** [comment]
> 不过这服务器节点被封了呀，不能用了。

因为有时效性，所以失效了。

**Comment by FLHonker** [comment]
no problem.
